# Generated by Django 4.2.30 on 2026-04-13 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(help_text='e.g., Computer Science, Mechanical', max_length=50)),
                ('batch_year', models.IntegerField(help_text='Year of admission, e.g., 2023')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(help_text='e.g., 1, 2, 3...')),
                ('attendance_percentage', models.FloatField(help_text='Percentage out of 100')),
                ('sgpa', models.FloatField(help_text='Semester Grade Point Average (0-10)')),
                ('cgpa', models.FloatField(help_text='Cumulative Grade Point Average (0-10)')),
                ('backlogs_current', models.IntegerField(default=0, help_text='Number of failed subjects in this semester')),
                ('fee_dues', models.BooleanField(default=False, help_text='Does the student have pending fee dues?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='academics.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
