# Generated by Django 5.2.13 on 2026-04-13 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('notes', models.TextField(help_text='Observation, discussion points, and planned actions.')),
                ('progress_status', models.CharField(choices=[('WORSENING', 'Worsening'), ('NO_CHANGE', 'No Change'), ('IMPROVING', 'Improving'), ('RESOLVED', 'Risk Resolved')], default='NO_CHANGE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'COUNSELOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='academics.studentprofile')),
            ],
        ),
    ]
